/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CvRouteImport } from './routes/cv'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsCategoryIndexRouteImport } from './routes/projects/$category/index'
import { Route as ProjectsCategoryProjectIdRouteImport } from './routes/projects/$category/$projectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CvRoute = CvRouteImport.update({
  id: '/cv',
  path: '/cv',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCategoryIndexRoute = ProjectsCategoryIndexRouteImport.update({
  id: '/$category/',
  path: '/$category/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCategoryProjectIdRoute =
  ProjectsCategoryProjectIdRouteImport.update({
    id: '/$category/$projectId',
    path: '/$category/$projectId',
    getParentRoute: () => ProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cv': typeof CvRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$category/$projectId': typeof ProjectsCategoryProjectIdRoute
  '/projects/$category/': typeof ProjectsCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cv': typeof CvRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$category/$projectId': typeof ProjectsCategoryProjectIdRoute
  '/projects/$category': typeof ProjectsCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cv': typeof CvRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$category/$projectId': typeof ProjectsCategoryProjectIdRoute
  '/projects/$category/': typeof ProjectsCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cv'
    | '/projects'
    | '/projects/'
    | '/projects/$category/$projectId'
    | '/projects/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cv'
    | '/projects'
    | '/projects/$category/$projectId'
    | '/projects/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cv'
    | '/projects'
    | '/projects/'
    | '/projects/$category/$projectId'
    | '/projects/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CvRoute: typeof CvRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv': {
      id: '/cv'
      path: '/cv'
      fullPath: '/cv'
      preLoaderRoute: typeof CvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$category/': {
      id: '/projects/$category/'
      path: '/$category'
      fullPath: '/projects/$category/'
      preLoaderRoute: typeof ProjectsCategoryIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$category/$projectId': {
      id: '/projects/$category/$projectId'
      path: '/$category/$projectId'
      fullPath: '/projects/$category/$projectId'
      preLoaderRoute: typeof ProjectsCategoryProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsCategoryProjectIdRoute: typeof ProjectsCategoryProjectIdRoute
  ProjectsCategoryIndexRoute: typeof ProjectsCategoryIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsCategoryProjectIdRoute: ProjectsCategoryProjectIdRoute,
  ProjectsCategoryIndexRoute: ProjectsCategoryIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CvRoute: CvRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
